# Generated by Django 2.2.16 on 2021-09-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Наименование')),
                ('name', models.CharField(max_length=100, verbose_name='Короткое наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='Версия')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код элемента')),
                ('value', models.TextField(verbose_name='Значение элемента')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handbooks.HandBook', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
